/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DAOMensalidades;
import entidade.Funcionarios;
import entidade.Mensalidades;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lab01_Aluno
 */
public class JFConsultaMensalidades extends javax.swing.JFrame {

    /**
     * Creates new form JFConsultaMensalidades
     */
    
    Funcionarios acesso_funci;
    
    public JFConsultaMensalidades(Funcionarios funci) {
        
        acesso_funci = funci;
        
        initComponents();
    }

    private JFConsultaMensalidades() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDCPeriodo = new com.toedter.calendar.JDateChooser();
        label1 = new java.awt.Label();
        jCBListarMensal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTMensalidade = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta de Mensalidades");
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        label1.setText("Período:");

        jCBListarMensal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Todos", "Pago", "Devendo" }));
        jCBListarMensal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCBListarMensalMouseClicked(evt);
            }
        });
        jCBListarMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBListarMensalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Listar por:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/x.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jCBListarMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBListarMensal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jDCPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTA DE MENSALIDADES");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTMensalidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do aluno", "Data do Vencimento", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTMensalidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMensalidadeMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTMensalidade);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(593, 653));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCBListarMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBListarMensalActionPerformed

    }//GEN-LAST:event_jCBListarMensalActionPerformed

    private void jTMensalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMensalidadeMouseClicked


    }//GEN-LAST:event_jTMensalidadeMouseClicked

    private void jDCPeriodoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDCPeriodoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDCPeriodoPropertyChange

    private void jCBListarMensalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBListarMensalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBListarMensalMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Mensalidades mensal = new Mensalidades();
            mensal.setStatus_mensal((String) jCBListarMensal.getSelectedItem());

            if (jCBListarMensal.getSelectedItem().equals("Selecionar")) {
                if (jDCPeriodo.getDate() == null) {
                    DefaultTableModel modeloMensal = (DefaultTableModel) jTMensalidade.getModel();

                    modeloMensal.getDataVector().removeAllElements();
                    modeloMensal.addRow(new Object[]{"", "SELECIONE O PERÍODO", "SELECIONAR STATUS"});
                    
                } else {
                    DefaultTableModel modeloMensal = (DefaultTableModel) jTMensalidade.getModel();

                    modeloMensal.getDataVector().removeAllElements();
                    modeloMensal.addRow(new Object[]{"", "", "SELECIONAR STATUS"});
                }
            }

            if (jCBListarMensal.getSelectedItem().equals("Pago")) {

                if (jDCPeriodo.getDate() == null) {

                    DefaultTableModel modeloMensal = (DefaultTableModel) jTMensalidade.getModel();

                    modeloMensal.getDataVector().removeAllElements();
                    modeloMensal.addRow(new Object[]{"", "SELECIONE O PERÍODO", ""});

                } else {
                    populaTabela(mensal);

                }

            }

            if (jCBListarMensal.getSelectedItem().equals("Devendo")) {

                if (jDCPeriodo.getDate() == null) {

                    DefaultTableModel modeloMensal = (DefaultTableModel) jTMensalidade.getModel();

                    modeloMensal.getDataVector().removeAllElements();
                    modeloMensal.addRow(new Object[]{"", "SELECIONE O PERÍODO", ""});

                } else {
                    populaTabela(mensal);
                }

            }

            if (jCBListarMensal.getSelectedItem().equals("Todos")) {

                if (jDCPeriodo.getDate() == null) {

                    DefaultTableModel modeloMensal = (DefaultTableModel) jTMensalidade.getModel();

                    modeloMensal.getDataVector().removeAllElements();
                    modeloMensal.addRow(new Object[]{"", "SELECIONE O PERÍODO", ""});

                } else {
                    populaTabela2(mensal);
                }

            }

        } catch (SQLException | ClassNotFoundException | ParseException ex) {
            Logger.getLogger(JFConsultaMensalidades.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseReleased

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        dispose();
        
        JFFormularioPrincipal form = new JFFormularioPrincipal(acesso_funci);
        form.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing
    public void populaTabela(Mensalidades mensali) throws SQLException, ClassNotFoundException, ParseException {

        Mensalidades men = new Mensalidades();

        men.setData_vencimento(jDCPeriodo.getDate());
        men.setStatus_mensal(mensali.getStatus_mensal());

        DAOMensalidades daoMensal = new DAOMensalidades();

        List<Mensalidades> resultado;
        resultado = daoMensal.ListarStatus(men);

        DefaultTableModel modelo = (DefaultTableModel) jTMensalidade.getModel();
        modelo.getDataVector().removeAllElements();

        if (resultado.isEmpty() == true) {
            modelo.getDataVector().removeAllElements();
            modelo.addRow(new Object[]{"VAZIO", "VAZIO", "VAZIO"});
        } else {

            modelo.getDataVector().removeAllElements();
            for (int i = 0; i < resultado.size(); i++) {
                modelo.addRow(new Object[]{resultado.get(i).getAluno().getNome_aluno(),
                    resultado.get(i).getData_vencimento(),
                    resultado.get(i).getStatus_mensal()});
            }
        }
    }

    public void populaTabela2(Mensalidades mensali) throws SQLException, ClassNotFoundException, ParseException {

        Mensalidades men = new Mensalidades();

        men.setData_vencimento(jDCPeriodo.getDate());

        DAOMensalidades daoMensal = new DAOMensalidades();

        List<Mensalidades> resultado;
        resultado = daoMensal.ListarStatus2(men);

        DefaultTableModel modelo = (DefaultTableModel) jTMensalidade.getModel();
        modelo.getDataVector().removeAllElements();

        if (resultado.isEmpty() == true) {
            modelo.getDataVector().removeAllElements();
            modelo.addRow(new Object[]{"VAZIO", "VAZIO", "VAZIO"});
        } else {

            modelo.getDataVector().removeAllElements();
            for (int i = 0; i < resultado.size(); i++) {
                modelo.addRow(new Object[]{
                    resultado.get(i).getAluno().getNome_aluno(),
                    resultado.get(i).getData_vencimento(),
                    resultado.get(i).getStatus_mensal()});
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConsultaMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConsultaMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConsultaMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConsultaMensalidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConsultaMensalidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBListarMensal;
    private com.toedter.calendar.JDateChooser jDCPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTMensalidade;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
