/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DAOFuncionarios;
import entidade.Funcionarios;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import relatorio.ConnectionFactory;
import relatorio.ReportUtils;

/**
 *
 * @author Lab01_Aluno
 */
public class JFFormularioPrincipal extends javax.swing.JFrame {

    //ARMAZENA O LOGIN ATUAL
    Funcionarios acesso_funci = null;

    public JFFormularioPrincipal(Funcionarios funci) {
        initComponents();
        acesso_funci = funci;
    }

    JFFormularioPrincipal() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLUsuario = new javax.swing.JLabel();
        jLFotoFunci = new javax.swing.JLabel();
        jLImagemHome = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMConsultarRelatorios = new javax.swing.JMenu();
        jMIRelatorioAlunos = new javax.swing.JMenuItem();
        jMIRelatorioFuncionarios = new javax.swing.JMenuItem();
        jMIRelatorioCargos = new javax.swing.JMenuItem();
        jMIRelatorioMensalidades = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMIGerenciarPermissoes = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuGerenciarAlunos = new javax.swing.JMenu();
        jMIGerenciarAlunos = new javax.swing.JMenuItem();
        jMIEfetuarPag = new javax.swing.JMenuItem();
        jMIConsultarMensal = new javax.swing.JMenuItem();
        jMenuGerenciarFuncionarios = new javax.swing.JMenu();
        jMIGerenciarFunci = new javax.swing.JMenuItem();
        jMenuGerenciarCargos = new javax.swing.JMenu();
        jMIGerenciarCargos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Academia");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jlHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hora:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Data:");

        jLUsuario.setText("Usuário: ");
        jLUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLFotoFunci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFotoFunci, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlHora, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLFotoFunci, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 546, 1145, 59);

        jLImagemHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLImagemHome.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLImagemHomeMouseMoved(evt);
            }
        });
        getContentPane().add(jLImagemHome);
        jLImagemHome.setBounds(0, 1, 1170, 620);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/Documents-icon.png"))); // NOI18N
        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/exit.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMConsultarRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/re.png"))); // NOI18N
        jMConsultarRelatorios.setText("Relatórios");

        jMIRelatorioAlunos.setText("Alunos");
        jMIRelatorioAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioAlunosActionPerformed(evt);
            }
        });
        jMConsultarRelatorios.add(jMIRelatorioAlunos);

        jMIRelatorioFuncionarios.setText("Funcionários");
        jMIRelatorioFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioFuncionariosActionPerformed(evt);
            }
        });
        jMConsultarRelatorios.add(jMIRelatorioFuncionarios);

        jMIRelatorioCargos.setText("Cargos");
        jMIRelatorioCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioCargosActionPerformed(evt);
            }
        });
        jMConsultarRelatorios.add(jMIRelatorioCargos);

        jMIRelatorioMensalidades.setText("Mensalidades");
        jMIRelatorioMensalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRelatorioMensalidadesActionPerformed(evt);
            }
        });
        jMConsultarRelatorios.add(jMIRelatorioMensalidades);

        jMenu1.add(jMConsultarRelatorios);

        jMenuBar1.add(jMenu1);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/bloggif_58224be5370ce.png"))); // NOI18N
        jMenu7.setText("Administração");

        jMIGerenciarPermissoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMIGerenciarPermissoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/tt.png"))); // NOI18N
        jMIGerenciarPermissoes.setText("Gerenciar Permissões");
        jMIGerenciarPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarPermissoesActionPerformed(evt);
            }
        });
        jMenu7.add(jMIGerenciarPermissoes);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/u.png"))); // NOI18N
        jMenu8.setText("Gerenciar Perfil");

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/eg.png"))); // NOI18N
        jMenu5.setText("Privacidade");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/bb.png"))); // NOI18N
        jMenuItem7.setText("Alterar Login");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu8.add(jMenu5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/b.png"))); // NOI18N
        jMenuItem6.setText("Alterar plano de fundo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenu7.add(jMenu8);

        jMenuBar1.add(jMenu7);

        jMenuGerenciarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/1297713679_list-add-user (Custom).png"))); // NOI18N
        jMenuGerenciarAlunos.setText("Alunos");

        jMIGerenciarAlunos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMIGerenciarAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/user_add.png"))); // NOI18N
        jMIGerenciarAlunos.setText("Gerenciar Alunos");
        jMIGerenciarAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMIGerenciarAlunosMouseClicked(evt);
            }
        });
        jMIGerenciarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarAlunosActionPerformed(evt);
            }
        });
        jMenuGerenciarAlunos.add(jMIGerenciarAlunos);

        jMIEfetuarPag.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMIEfetuarPag.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/bloggif_580551574f011.png"))); // NOI18N
        jMIEfetuarPag.setText("Efetuar Pagamento");
        jMIEfetuarPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEfetuarPagActionPerformed(evt);
            }
        });
        jMenuGerenciarAlunos.add(jMIEfetuarPag);

        jMIConsultarMensal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMIConsultarMensal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/m.png"))); // NOI18N
        jMIConsultarMensal.setText("Consultar Mensalidades");
        jMIConsultarMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultarMensalActionPerformed(evt);
            }
        });
        jMenuGerenciarAlunos.add(jMIConsultarMensal);

        jMenuBar1.add(jMenuGerenciarAlunos);

        jMenuGerenciarFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/administrator-icon (Custom).png"))); // NOI18N
        jMenuGerenciarFuncionarios.setText("Funcionários");

        jMIGerenciarFunci.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMIGerenciarFunci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/Office-Customer-Male-Light-icon.png"))); // NOI18N
        jMIGerenciarFunci.setText("Gerenciar Funcionários");
        jMIGerenciarFunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarFunciActionPerformed(evt);
            }
        });
        jMenuGerenciarFuncionarios.add(jMIGerenciarFunci);

        jMenuBar1.add(jMenuGerenciarFuncionarios);

        jMenuGerenciarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/gg.png"))); // NOI18N
        jMenuGerenciarCargos.setText("Cargos");

        jMIGerenciarCargos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMIGerenciarCargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/ggg.png"))); // NOI18N
        jMIGerenciarCargos.setText("Gerenciar Cargos");
        jMIGerenciarCargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIGerenciarCargosActionPerformed(evt);
            }
        });
        jMenuGerenciarCargos.add(jMIGerenciarCargos);

        jMenuBar1.add(jMenuGerenciarCargos);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/bloggif_580552985b6bd.png"))); // NOI18N
        jMenu3.setText("Sobre");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Informações do Sistema");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1181, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMIGerenciarAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMIGerenciarAlunosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIGerenciarAlunosMouseClicked

    private void jMIGerenciarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarAlunosActionPerformed
        try {
            // TODO add your handling code here:
            
            dispose();

            JFGerenciarAlunos geralu = new JFGerenciarAlunos(acesso_funci);
            geralu.setVisible(true);

        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMIGerenciarAlunosActionPerformed

    private void jMIEfetuarPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEfetuarPagActionPerformed
        try {
            // TODO add your handling code here:

            dispose();
            
            JFMensalidades gerMensal = new JFMensalidades(acesso_funci);
            gerMensal.setVisible(true);
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMIEfetuarPagActionPerformed

    private void jMIGerenciarFunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarFunciActionPerformed
        try {
            
            dispose();
            
            JFGerenciarFuncionarios fun = new JFGerenciarFuncionarios(acesso_funci);
            fun.setVisible(true);
        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMIGerenciarFunciActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFLoginInicio formlog = new JFLoginInicio();
        formlog.setVisible(true);

        dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            //this.setExtendedState(MAXIMIZED_BOTH);
            //JFFormularioPrincipal.cadastro=false;
            Date dataSistema = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            jlData.setText(formato.format(dataSistema));

            Timer timer = new Timer(1000, new hora());
            timer.start();

            Funcionarios funci = new Funcionarios();
            DAOFuncionarios daofunci = new DAOFuncionarios();
            funci = daofunci.PesquisaLogin(acesso_funci);

            if (funci.getWallpaper_funci() != null) {
                ImageIcon plano_fundo = new ImageIcon((byte[]) funci.getWallpaper_funci());
                jLImagemHome.setIcon(new ImageIcon(plano_fundo.getImage().getScaledInstance(jLImagemHome.getWidth(), jLImagemHome.getHeight(), Image.SCALE_DEFAULT)));
            } else {

            }

            if (funci.getFoto_funcionario() != null) {
                ImageIcon perfil = new ImageIcon((byte[]) funci.getFoto_funcionario());

                jLFotoFunci.setIcon(new ImageIcon(perfil.getImage().getScaledInstance(jLFotoFunci.getWidth(), jLFotoFunci.getHeight(), Image.SCALE_DEFAULT)));
            }

            jLUsuario.setText(jLUsuario.getText() + acesso_funci.getNome());

            //CONFIGURA PERMISSÕES
            if (acesso_funci.getCargo().isGerenciar_aluno() == true) {
                jMIGerenciarAlunos.setEnabled(true);
            } else {
                jMIGerenciarAlunos.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_funci() == true) {

                jMIGerenciarFunci.setEnabled(true);
            } else {
                jMIGerenciarFunci.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_cargo() == true) {

                jMIGerenciarCargos.setEnabled(true);

            } else {
                jMIGerenciarCargos.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_permissoes() == true) {
                jMIGerenciarPermissoes.setEnabled(true);
            } else {
                jMIGerenciarPermissoes.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_relatorio() == true) {
                jMIRelatorioAlunos.setEnabled(true);
                jMIRelatorioFuncionarios.setEnabled(true);
                jMIRelatorioCargos.setEnabled(true);
                jMIRelatorioMensalidades.setEnabled(true);
            } else {
                jMIRelatorioAlunos.setEnabled(false);
                jMIRelatorioFuncionarios.setEnabled(false);
                jMIRelatorioCargos.setEnabled(false);
                jMIRelatorioMensalidades.setEnabled(false);
                
            }
            if (acesso_funci.getCargo().isConsulta_mensal() == true) {
                jMIConsultarMensal.setEnabled(true);
            } else {
                jMIConsultarMensal.setEnabled(false);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formWindowOpened

    private void jMIConsultarMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultarMensalActionPerformed

        dispose();
        
        JFConsultaMensalidades con = new JFConsultaMensalidades(acesso_funci);
        con.setVisible(true);
    }//GEN-LAST:event_jMIConsultarMensalActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        ///Redimensionar imagem
        JFileChooser escolha_arq = new JFileChooser();
        escolha_arq.setDialogTitle("Selecione a Foto do Aluno");
        escolha_arq.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int opc = escolha_arq.showOpenDialog(this);

        if (opc == JFileChooser.APPROVE_OPTION) {
            try {
                File arquivo = new File("Caminho");
                arquivo = escolha_arq.getSelectedFile();
                String nome_arquivo = arquivo.getAbsolutePath();

                ImageIcon newwallpaper = new ImageIcon(nome_arquivo);
                jLImagemHome.setIcon(new ImageIcon(newwallpaper.getImage().getScaledInstance(jLImagemHome.getWidth(), jLImagemHome.getHeight(), Image.SCALE_AREA_AVERAGING)));

                Funcionarios funci = new Funcionarios();
                funci.setId_funcionario(acesso_funci.getId_funcionario());
                funci.setCaminho_wallpaper(nome_arquivo);

                DAOFuncionarios daofunci = new DAOFuncionarios();
                daofunci.novoWallpaper(funci);

                Funcionarios fun = new Funcionarios();
                fun = daofunci.PesquisaLogin(acesso_funci);

                acesso_funci = fun;

                ImageIcon wallpaper = new ImageIcon(acesso_funci.getWallpaper_funci());
                jLImagemHome.setIcon(new ImageIcon(wallpaper.getImage().getScaledInstance(jLImagemHome.getWidth(), jLImagemHome.getHeight(), Image.SCALE_AREA_AVERAGING)));

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        dispose();
        
        JFLoginAntigo formlog = new JFLoginAntigo(acesso_funci);
        formlog.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMIGerenciarCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarCargosActionPerformed
        try {
            // TODO add your handling code here:

            dispose();
            
            JFGerenciarCargos formcargo = new JFGerenciarCargos(acesso_funci);
            formcargo.setVisible(true);

        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMIGerenciarCargosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        dispose();
        
        JFSobre jf = new JFSobre(acesso_funci);
        jf.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        this.setDefaultCloseOperation(1);
        
        JFLoginInicio form = new JFLoginInicio();
        form.setVisible(true);

    }//GEN-LAST:event_formWindowClosing

    private void jMIGerenciarPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIGerenciarPermissoesActionPerformed
        try {
            // TODO add your handling code here:

            dispose();
            
            JFGerenciarPermissoes form = new JFGerenciarPermissoes(acesso_funci);
            form.setVisible(true);

        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMIGerenciarPermissoesActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jLImagemHomeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLImagemHomeMouseMoved

    }//GEN-LAST:event_jLImagemHomeMouseMoved

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:

        try {
            //ATUALIZA AS INFORMAÇÕES DE LOGIN

            DAOFuncionarios daofunci = new DAOFuncionarios();
            acesso_funci = daofunci.PesquisaLogin(acesso_funci);

            if (acesso_funci.getFoto_funcionario() != null) {
                ImageIcon foto_aluno = new ImageIcon(acesso_funci.getFoto_funcionario());
                jLFotoFunci.setIcon(new ImageIcon(foto_aluno.getImage().getScaledInstance(jLFotoFunci.getWidth(), jLFotoFunci.getHeight(), Image.SCALE_AREA_AVERAGING)));
            } else {

            }

            if (acesso_funci.getWallpaper_funci() != null) {
                ImageIcon plano_fundo = new ImageIcon((byte[]) acesso_funci.getWallpaper_funci());
                jLImagemHome.setIcon(new ImageIcon(plano_fundo.getImage().getScaledInstance(jLImagemHome.getWidth(), jLImagemHome.getHeight(), Image.SCALE_DEFAULT)));
            } else {

            }

            //CONFIGURA PERMISSÕES
            if (acesso_funci.getCargo().isGerenciar_aluno() == true) {
                jMIGerenciarAlunos.setEnabled(true);
            } else {
                jMIGerenciarAlunos.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_funci() == true) {

                jMIGerenciarFunci.setEnabled(true);
            } else {
                jMIGerenciarFunci.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_cargo() == true) {

                jMIGerenciarCargos.setEnabled(true);

            } else {
                jMIGerenciarCargos.setEnabled(false);
            }

            if (acesso_funci.getCargo().isGerenciar_permissoes() == true) {
                jMIGerenciarPermissoes.setEnabled(true);
            } else {
                jMIGerenciarPermissoes.setEnabled(false);
            }

//            if (acesso_funci.getCargo().isGerenciar_relatorio() == true) {
//                jMIConsultarRelatorios.setEnabled(true);
//            } else {
//                jMIConsultarRelatorios.setEnabled(false);
//            }
            if (acesso_funci.getCargo().isConsulta_mensal() == true) {
                jMIConsultarMensal.setEnabled(true);
            } else {
                jMIConsultarMensal.setEnabled(false);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JFFormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void jMIRelatorioAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioAlunosActionPerformed
        // TODO add your handling code here:
        
        abrirRelatorioAlunos();
        
    }//GEN-LAST:event_jMIRelatorioAlunosActionPerformed

    private void jMIRelatorioFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioFuncionariosActionPerformed
        // TODO add your handling code here:
        
        abrirRelatorioFuncionarios();
    }//GEN-LAST:event_jMIRelatorioFuncionariosActionPerformed

    private void jMIRelatorioCargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioCargosActionPerformed
        // TODO add your handling code here:
        
        abrirRelatorioCargos();
        
    }//GEN-LAST:event_jMIRelatorioCargosActionPerformed

    private void jMIRelatorioMensalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRelatorioMensalidadesActionPerformed
        // TODO add your handling code here:
        
        abrirRelatorioMensal();
        
    }//GEN-LAST:event_jMIRelatorioMensalidadesActionPerformed

    
    public void abrirRelatorioAlunos() {
 
        /*
         * Obtendo o arquivo do relatório.
         * Note que estamos utilizando um InputStream para obter o arquivo que
         * está dentro do nosso projeto. Fazendo isso, não teremos problema
         * quando nosso projeto for empacotado em um .jar.
         *
         * Note que o caminho do .jasper inicia com /, ou seja, a raiz da
         * localização das classes compiladas do nosso projeto
         * (o pacote default).
         *
         * Utilize a aba Files (canto superior esquerdo) e veja que os arquivos
         * .jasper e .jrxml são copiados para o diretório /build/classes
         * e por consequencia para o .jar que for criado.
         *
         * Se não os estiver vendo, mande dar um Clean and Build no projeto
         * (botão direito no nó raiz do projeto, Clean and Build (Limpar e Construir)
         *
         */
        InputStream inputStream = getClass().getResourceAsStream( "/RelatorioAlunos.jasper" );
 
        // mapa de parâmetros do relatório (ainda vamos aprender a usar)
        Map parametros = new HashMap();
 
        try {
 
            // abre o relatório
            ReportUtils.openReport( "Relatório de Alunos", inputStream, parametros,
                    ConnectionFactory.getAcademiaConnection());
 
        } catch ( SQLException | JRException exc ) {
            exc.printStackTrace();
        }
 
    }
    
    public void abrirRelatorioFuncionarios() {
 
        /*
         * Obtendo o arquivo do relatório.
         * Note que estamos utilizando um InputStream para obter o arquivo que
         * está dentro do nosso projeto. Fazendo isso, não teremos problema
         * quando nosso projeto for empacotado em um .jar.
         *
         * Note que o caminho do .jasper inicia com /, ou seja, a raiz da
         * localização das classes compiladas do nosso projeto
         * (o pacote default).
         *
         * Utilize a aba Files (canto superior esquerdo) e veja que os arquivos
         * .jasper e .jrxml são copiados para o diretório /build/classes
         * e por consequencia para o .jar que for criado.
         *
         * Se não os estiver vendo, mande dar um Clean and Build no projeto
         * (botão direito no nó raiz do projeto, Clean and Build (Limpar e Construir)
         *
         */
        InputStream inputStream = getClass().getResourceAsStream( "/RelatorioFuncionarios.jasper" );
 
        // mapa de parâmetros do relatório (ainda vamos aprender a usar)
        Map parametros = new HashMap();
 
        try {
 
            // abre o relatório
            ReportUtils.openReport( "Relatório de Funcionários", inputStream, parametros,
                    ConnectionFactory.getAcademiaConnection());
 
        } catch ( SQLException | JRException exc ) {
            exc.printStackTrace();
        }
 
    }
    
    public void abrirRelatorioCargos() {
 
        /*
         * Obtendo o arquivo do relatório.
         * Note que estamos utilizando um InputStream para obter o arquivo que
         * está dentro do nosso projeto. Fazendo isso, não teremos problema
         * quando nosso projeto for empacotado em um .jar.
         *
         * Note que o caminho do .jasper inicia com /, ou seja, a raiz da
         * localização das classes compiladas do nosso projeto
         * (o pacote default).
         *
         * Utilize a aba Files (canto superior esquerdo) e veja que os arquivos
         * .jasper e .jrxml são copiados para o diretório /build/classes
         * e por consequencia para o .jar que for criado.
         *
         * Se não os estiver vendo, mande dar um Clean and Build no projeto
         * (botão direito no nó raiz do projeto, Clean and Build (Limpar e Construir)
         *
         */
        InputStream inputStream = getClass().getResourceAsStream( "/RelatorioCargos.jasper" );
 
        // mapa de parâmetros do relatório (ainda vamos aprender a usar)
        Map parametros = new HashMap();
 
        try {
 
            // abre o relatório
            ReportUtils.openReport( "Relatório de Cargos", inputStream, parametros,
                    ConnectionFactory.getAcademiaConnection());
 
        } catch ( SQLException | JRException exc ) {
            exc.printStackTrace();
        }
 
    }
    
    public void abrirRelatorioMensal() {
 
        /*
         * Obtendo o arquivo do relatório.
         * Note que estamos utilizando um InputStream para obter o arquivo que
         * está dentro do nosso projeto. Fazendo isso, não teremos problema
         * quando nosso projeto for empacotado em um .jar.
         *
         * Note que o caminho do .jasper inicia com /, ou seja, a raiz da
         * localização das classes compiladas do nosso projeto
         * (o pacote default).
         *
         * Utilize a aba Files (canto superior esquerdo) e veja que os arquivos
         * .jasper e .jrxml são copiados para o diretório /build/classes
         * e por consequencia para o .jar que for criado.
         *
         * Se não os estiver vendo, mande dar um Clean and Build no projeto
         * (botão direito no nó raiz do projeto, Clean and Build (Limpar e Construir)
         *
         */
        InputStream inputStream = getClass().getResourceAsStream( "/RelatorioMensalidades.jasper" );
 
        // mapa de parâmetros do relatório (ainda vamos aprender a usar)
        Map parametros = new HashMap();
 
        try {
 
            // abre o relatório
            ReportUtils.openReport( "Relatório de Mensalidades", inputStream, parametros,
                    ConnectionFactory.getAcademiaConnection());
 
        } catch ( SQLException | JRException exc ) {
            exc.printStackTrace();
        }
 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLFotoFunci;
    private javax.swing.JLabel jLImagemHome;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMConsultarRelatorios;
    private javax.swing.JMenuItem jMIConsultarMensal;
    private javax.swing.JMenuItem jMIEfetuarPag;
    private javax.swing.JMenuItem jMIGerenciarAlunos;
    private javax.swing.JMenuItem jMIGerenciarCargos;
    public javax.swing.JMenuItem jMIGerenciarFunci;
    private javax.swing.JMenuItem jMIGerenciarPermissoes;
    private javax.swing.JMenuItem jMIRelatorioAlunos;
    private javax.swing.JMenuItem jMIRelatorioCargos;
    private javax.swing.JMenuItem jMIRelatorioFuncionarios;
    private javax.swing.JMenuItem jMIRelatorioMensalidades;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGerenciarAlunos;
    private javax.swing.JMenu jMenuGerenciarCargos;
    private javax.swing.JMenu jMenuGerenciarFuncionarios;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlHora;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jlHora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }

}
