/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DAOCargos;
import entidade.Cargos;
import entidade.Funcionarios;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jocélia
 */
public final class JFGerenciarPermissoes extends javax.swing.JFrame {

    /**
     * Creates new form JFGerenciarPermissoes
     */
    Funcionarios acesso_funci = null;

    public JFGerenciarPermissoes(Funcionarios funci) throws ClassNotFoundException, SQLException, ParseException {
        initComponents();
        populaTabelaCargo();

        acesso_funci = funci;
    }

    private JFGerenciarPermissoes() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFProcurarCargo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCargos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCBCadAluno = new javax.swing.JCheckBox();
        jCBEfetuarPag = new javax.swing.JCheckBox();
        jCBConsultarMensal = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCBCadFunci = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jCBCadCargo = new javax.swing.JCheckBox();
        jPGerenciarAdmin = new javax.swing.JPanel();
        jCBGerenciarPermissoes = new javax.swing.JCheckBox();
        jPGerenciarAdmin1 = new javax.swing.JPanel();
        jCBGerenciarRelatorios = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jBAtualizarPermissao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione um Cargo"));

        jLabel1.setText("Procurar:");

        jTFProcurarCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFProcurarCargoKeyReleased(evt);
            }
        });

        jTCargos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCargosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTCargos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jTFProcurarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFProcurarCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissôes para os MENUS"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("... para Gerenciar Alunos"));

        jCBCadAluno.setText("Gerenciar Alunos");
        jCBCadAluno.setEnabled(false);

        jCBEfetuarPag.setText("Efetuar Pagamento");
        jCBEfetuarPag.setEnabled(false);

        jCBConsultarMensal.setText("Consultar Mensalidades");
        jCBConsultarMensal.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBCadAluno)
                    .addComponent(jCBConsultarMensal)
                    .addComponent(jCBEfetuarPag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCBCadAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBEfetuarPag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBConsultarMensal))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("... para Gerenciar Funcionários"));

        jCBCadFunci.setText("Gerenciar Funcionários");
        jCBCadFunci.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBCadFunci)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBCadFunci)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("... para Gerenciar Cargos"));

        jCBCadCargo.setText("Gerenciar Cargos");
        jCBCadCargo.setEnabled(false);
        jCBCadCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCadCargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBCadCargo)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBCadCargo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPGerenciarAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder("... para Administração"));

        jCBGerenciarPermissoes.setText("Gerenciar Permissões");
        jCBGerenciarPermissoes.setEnabled(false);
        jCBGerenciarPermissoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGerenciarPermissoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGerenciarAdminLayout = new javax.swing.GroupLayout(jPGerenciarAdmin);
        jPGerenciarAdmin.setLayout(jPGerenciarAdminLayout);
        jPGerenciarAdminLayout.setHorizontalGroup(
            jPGerenciarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGerenciarAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBGerenciarPermissoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPGerenciarAdminLayout.setVerticalGroup(
            jPGerenciarAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGerenciarAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBGerenciarPermissoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPGerenciarAdmin1.setBorder(javax.swing.BorderFactory.createTitledBorder("... para Gerenciar Arquivo"));

        jCBGerenciarRelatorios.setText("Gerenciar Relatórios");
        jCBGerenciarRelatorios.setEnabled(false);
        jCBGerenciarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGerenciarRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGerenciarAdmin1Layout = new javax.swing.GroupLayout(jPGerenciarAdmin1);
        jPGerenciarAdmin1.setLayout(jPGerenciarAdmin1Layout);
        jPGerenciarAdmin1Layout.setHorizontalGroup(
            jPGerenciarAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGerenciarAdmin1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBGerenciarRelatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPGerenciarAdmin1Layout.setVerticalGroup(
            jPGerenciarAdmin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGerenciarAdmin1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBGerenciarRelatorios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPGerenciarAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPGerenciarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPGerenciarAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPGerenciarAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jBAtualizarPermissao.setText("Atualizar Permissão");
        jBAtualizarPermissao.setEnabled(false);
        jBAtualizarPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarPermissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAtualizarPermissao)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAtualizarPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFProcurarCargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFProcurarCargoKeyReleased
        try {
            // TODO add your handling code here:

            populaTabelaCargo();

        } catch (ClassNotFoundException | SQLException | ParseException ex) {
            Logger.getLogger(JFGerenciarPermissoes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTFProcurarCargoKeyReleased

    private void jTCargosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCargosMouseClicked
        // TODO add your handling code here:

        if (jTCargos.getSelectedRow() != -1) {

            try {

                jBAtualizarPermissao.setEnabled(true);

                preparaCheckBoxs();

                DefaultTableModel modelo = (DefaultTableModel) jTCargos.getModel();

                Cargos cargo = new Cargos();
                cargo.setId_cargo((int) modelo.getValueAt(jTCargos.getSelectedRow(), 0));

                DAOCargos daocargo = new DAOCargos();
                cargo = daocargo.buscarCargo(cargo);

                jCBCadAluno.setSelected(cargo.isGerenciar_aluno());

                jCBCadFunci.setSelected(cargo.isGerenciar_funci());

                jCBCadCargo.setSelected(cargo.isGerenciar_cargo());

                jCBGerenciarPermissoes.setSelected(cargo.isGerenciar_permissoes());

                jCBGerenciarRelatorios.setSelected(cargo.isGerenciar_relatorio());

                jCBConsultarMensal.setSelected(cargo.isConsulta_mensal());

                jCBEfetuarPag.setSelected(cargo.isEfetuar_pag());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JFGerenciarPermissoes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jTCargosMouseClicked

    private void jCBCadCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCadCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCadCargoActionPerformed

    private void jCBGerenciarPermissoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGerenciarPermissoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBGerenciarPermissoesActionPerformed

    private void jCBGerenciarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGerenciarRelatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBGerenciarRelatoriosActionPerformed

    private void jBAtualizarPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarPermissaoActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel modelo = (DefaultTableModel) jTCargos.getModel();

            if (jTCargos.getSelectedRow() != -1) {

                Cargos cargo = new Cargos();

                cargo.setId_cargo((int) modelo.getValueAt(jTCargos.getSelectedRow(), 0));

                cargo.setGerenciar_aluno(jCBCadAluno.isSelected());

                cargo.setGerenciar_funci(jCBCadFunci.isSelected());

                cargo.setGerenciar_cargo(jCBCadCargo.isSelected());

                cargo.setGerenciar_relatorio(jCBGerenciarRelatorios.isSelected());

                cargo.setGerenciar_permissoes(jCBGerenciarPermissoes.isSelected());

                cargo.setConsulta_mensal(jCBConsultarMensal.isSelected());

                cargo.setEfetuar_pag(jCBEfetuarPag.isSelected());

                DAOCargos daocargo = new DAOCargos();
                daocargo.atualizarPermissao(cargo);

                jCBGerenciarRelatorios.setEnabled(false);
                jCBGerenciarPermissoes.setEnabled(false);
                jCBCadAluno.setEnabled(false);
                jCBEfetuarPag.setEnabled(false);
                jCBConsultarMensal.setEnabled(false);
                jCBCadFunci.setEnabled(false);
                jCBCadCargo.setEnabled(false);

                jCBGerenciarRelatorios.setSelected(false);
                jCBGerenciarPermissoes.setSelected(false);
                jCBCadAluno.setSelected(false);
                jCBEfetuarPag.setSelected(false);
                jCBConsultarMensal.setSelected(false);
                jCBCadFunci.setSelected(false);
                jCBCadCargo.setSelected(false);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JFGerenciarPermissoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBAtualizarPermissaoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        JFFormularioPrincipal form = new JFFormularioPrincipal(acesso_funci);
        form.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing

    public void preparaCheckBoxs() {

        jCBGerenciarRelatorios.setEnabled(true);
        jCBGerenciarPermissoes.setEnabled(true);
        jCBCadAluno.setEnabled(true);
        jCBEfetuarPag.setEnabled(true);
        jCBConsultarMensal.setEnabled(true);
        jCBCadFunci.setEnabled(true);
        jCBCadCargo.setEnabled(true);

    }

    public void organizaCheckBoxs() {

        jCBCadAluno.setSelected(false);

        jCBCadFunci.setSelected(false);

        jCBCadCargo.setSelected(false);

        jCBCadAluno.setEnabled(false);

        jCBCadFunci.setEnabled(false);

        jCBCadCargo.setEnabled(false);

    }

    public void populaTabelaCargo() throws ClassNotFoundException, SQLException, ParseException {

        try {

            Cargos cargo = new Cargos();
            cargo.setNome_cargo(jTFProcurarCargo.getText());

            DAOCargos daocargo = new DAOCargos();
            List<Cargos> lista = daocargo.PesquisaCargo(cargo);

            DefaultTableModel modelo = (DefaultTableModel) jTCargos.getModel();
            modelo.getDataVector().removeAllElements();

            for (int i = 0; i < lista.size(); i++) {
                modelo.addRow(new Object[]{
                    lista.get(i).getId_cargo(),
                    lista.get(i).getNome_cargo()
                });
            }

            if (lista.isEmpty() == true) {

                for (int i = 0; i < 1; i++) {
                    modelo.addRow(new Object[]{null});
                    modelo.removeRow(i);
                    modelo.addRow(new Object[]{"VAZIO", "VAZIO", "VAZIO"});
                }

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JFGerenciarCargos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFGerenciarPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFGerenciarPermissoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtualizarPermissao;
    private javax.swing.JCheckBox jCBCadAluno;
    private javax.swing.JCheckBox jCBCadCargo;
    private javax.swing.JCheckBox jCBCadFunci;
    private javax.swing.JCheckBox jCBConsultarMensal;
    private javax.swing.JCheckBox jCBEfetuarPag;
    private javax.swing.JCheckBox jCBGerenciarPermissoes;
    private javax.swing.JCheckBox jCBGerenciarRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPGerenciarAdmin;
    private javax.swing.JPanel jPGerenciarAdmin1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCargos;
    private javax.swing.JTextField jTFProcurarCargo;
    // End of variables declaration//GEN-END:variables
}
