/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import dao.DAOFuncionarios;
import entidade.Cargos;
import entidade.Funcionarios;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lab01_Aluno
 */
public class JFLoginNovo extends javax.swing.JFrame {

    /**
     * Creates new form JFLoginNovo
     */
    Funcionarios acesso_funci = null;

    public JFLoginNovo(Funcionarios funci) {
        initComponents();
        acesso_funci = funci;
    }

    public JFLoginNovo() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPFNovaSenha = new javax.swing.JPasswordField();
        jPFConfirmaSenha = new javax.swing.JPasswordField();
        jTFUsuario = new javax.swing.JTextField();
        jCBStatusSenha = new javax.swing.JCheckBox();
        jCBStatusUsuario = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Login");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inter_face/imagem/bloggif_5805611bcc99c.png"))); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Confirmar a nova senha:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Digite a nova senha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Digite o novo Usuário:");

        jPFNovaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFNovaSenhaKeyReleased(evt);
            }
        });

        jPFConfirmaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPFConfirmaSenhaKeyReleased(evt);
            }
        });

        jTFUsuario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jTFUsuarioAncestorRemoved(evt);
            }
        });
        jTFUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuarioActionPerformed(evt);
            }
        });
        jTFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFUsuarioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPFNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPFConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPFNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPFConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jCBStatusSenha.setEnabled(false);

        jCBStatusUsuario.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alteração para o novo Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jCBStatusUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jCBStatusSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jCBStatusUsuario)
                .addGap(19, 19, 19)
                .addComponent(jCBStatusSenha)
                .addGap(19, 19, 19)
                .addComponent(jButton1))
        );

        setSize(new java.awt.Dimension(660, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            if (jCBStatusSenha.isSelected() == true && jCBStatusUsuario.isSelected() == true) {


                    Cargos cargo = new Cargos();
                    cargo.setId_cargo(acesso_funci.getCargo().getId_cargo());

                    Funcionarios funci = new Funcionarios();
                    funci.setConfirma_usuario(acesso_funci.getUsuario());
                    funci.setConfirma_senha(acesso_funci.getSenha());
                    funci.setCargo(cargo);

                    DAOFuncionarios daofunci = new DAOFuncionarios();

                    funci.setUsuario(jTFUsuario.getText());
                    funci.setSenha(String.valueOf(jPFNovaSenha.getPassword()));

                    daofunci.novoLogin(funci);

                    acesso_funci = daofunci.PesquisaLogin(funci);

                    JFFormularioPrincipal form = new JFFormularioPrincipal(acesso_funci);
                    form.setVisible(true);

                    this.setVisible(false);
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JFLoginNovo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTFUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioActionPerformed

    private void jPFNovaSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFNovaSenhaKeyReleased
        // TODO add your handling code here:

        if (!String.valueOf(jPFNovaSenha.getPassword()).equals(String.valueOf(jPFConfirmaSenha.getPassword()))) {

            jPFNovaSenha.setBackground(Color.RED);
            jPFConfirmaSenha.setBackground(Color.RED);

            jCBStatusSenha.setText("As SENHAS não coincidem !");
            jCBStatusSenha.setSelected(false);

        } else {

            jPFConfirmaSenha.setBackground(Color.WHITE);
            jPFNovaSenha.setBackground(Color.WHITE);

            jCBStatusSenha.setText("As SENHAS coincidem !");
            jCBStatusSenha.setSelected(true);

            if (String.valueOf(jPFNovaSenha.getPassword()).isEmpty() && String.valueOf(jPFConfirmaSenha.getPassword()).isEmpty()) {

                jPFNovaSenha.setBackground(Color.RED);
                jPFConfirmaSenha.setBackground(Color.RED);

                jCBStatusSenha.setText("SENHA NULA não é permitido!");
                jCBStatusSenha.setSelected(false);

            }

        }


    }//GEN-LAST:event_jPFNovaSenhaKeyReleased

    private void jPFConfirmaSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFConfirmaSenhaKeyReleased
        // TODO add your handling code here:

        if (!String.valueOf(jPFConfirmaSenha.getPassword()).equals(String.valueOf(jPFNovaSenha.getPassword()))) {

            jPFConfirmaSenha.setBackground(Color.RED);
            jPFNovaSenha.setBackground(Color.RED);

            jCBStatusSenha.setText("As SENHAS não coincidem !");
            jCBStatusSenha.setSelected(false);

        } else {

            jPFNovaSenha.setBackground(Color.WHITE);

            jPFConfirmaSenha.setBackground(Color.WHITE);

            jCBStatusSenha.setText("As SENHAS coincidem !");
            jCBStatusSenha.setSelected(true);

            if (String.valueOf(jPFConfirmaSenha.getPassword()).isEmpty() && String.valueOf(jPFNovaSenha.getPassword()).isEmpty()) {

                jPFConfirmaSenha.setBackground(Color.RED);
                jPFNovaSenha.setBackground(Color.RED);

                jCBStatusSenha.setText("SENHA NULA não é permitido !");
                jCBStatusSenha.setSelected(false);

            }

        }


    }//GEN-LAST:event_jPFConfirmaSenhaKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(rootPane, "USUÁRIO e SENHA não alterados");

        JFFormularioPrincipal form = new JFFormularioPrincipal(acesso_funci);
        form.setVisible(true);

    }//GEN-LAST:event_formWindowClosed

    private void jTFUsuarioAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTFUsuarioAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioAncestorRemoved

    private void jTFUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUsuarioKeyReleased
        // TODO add your handling code here:

        if (jTFUsuario.getText().isEmpty()) {

            jTFUsuario.setBackground(Color.RED);
            jCBStatusUsuario.setSelected(false);
            jCBStatusUsuario.setText("USUÁRIO nulo não é permitido !");
        } else {
            jTFUsuario.setBackground(Color.WHITE);
            jCBStatusUsuario.setSelected(true);
            jCBStatusUsuario.setText("USUÁRIO permitido !");
        }

    }//GEN-LAST:event_jTFUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLoginNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLoginNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCBStatusSenha;
    private javax.swing.JCheckBox jCBStatusUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPFConfirmaSenha;
    private javax.swing.JPasswordField jPFNovaSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFUsuario;
    // End of variables declaration//GEN-END:variables
}
